import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import petstoreSidebar from './docs/petstore/sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 为每个顶级目录配置独立的侧边栏，实现"从二级菜单开始展示"的效果
  overview: [
    {
      type: 'autogenerated',
      dirName: 'index_overview', // '.' 即当前 docs 文件夹
    },
  ],
  spot: [
    {
      type: 'autogenerated',
      dirName: 'spot', // '.' 即当前 docs 文件夹
    },
  ],
  futures: [
    {
      type: 'autogenerated',
      dirName: 'futures', // '.' 即当前 docs 文件夹
    },
  ],
  'margin-spot': [
    {
      type: 'autogenerated',
      dirName: 'margin-spot', // '.' 即当前 docs 文件夹
    },
  ],
  'copy-trading': [
    {
      type: 'autogenerated',
      dirName: 'copy-trading', // '.' 即当前 docs 文件夹
    },
  ],
  'futures-copy': [
    {
      type: 'autogenerated',
      dirName: 'futures-copy', // '.' 即当前 docs 文件夹
    },
  ],
  'trading-third-party': [
    {
      type: 'autogenerated',
      dirName: 'trading-third-party', // '.' 即当前 docs 文件夹
    },
  ],
  'user-center': [
    {
      type: 'autogenerated',
      dirName: 'user-center', // '.' 即当前 docs 文件夹
    },
  ],
  'Referral Commission': [
    {
      type: 'autogenerated',
      dirName: 'Referral Commission', // '.' 即当前 docs 文件夹
    },
  ],
  loan: [
    {
      type: 'autogenerated',
      dirName: 'loan', // '.' 即当前 docs 文件夹
    },
  ],
  changelog: ['changelog/index'],
  api: petstoreSidebar,
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
