// sidebarsApi.ts
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// 专门给 API 文档（path: api_docs / api-docs）用的 sidebar 配置
// 用自动生成，避免手写 doc id 对不上导致报错
const sidebars: SidebarsConfig = {
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // 从 API 文档根目录开始自动生成侧边栏
    },
  ],
};

export default sidebars;
