openapi: 3.0.3
info:
  title: 合约
  description: 合约接口文档
  termsOfService: "urn:tos"
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
  version: '1.0'

servers:
  - url: "https://fapi.xt.com"
    description: Inferred Url

tags:
  - name: basic-error-controller
    description: Basic Error Controller
  - name: listenKey
    description: Listen Key Controller
  - name: operation-handler
    description: Operation Handler
  - name: symbol-controller
    description: Symbol Controller
  - name: web-mvc-links-handler
    description: Web Mvc Links Handler
  - name: 内部接口
    description: Internal Controller
  - name: 分享
    description: Share Controller
  - name: 合约告知书
    description: Notice Controller
  - name: 合约聪明钱
    description: Smart Money Controller
  - name: 合约聪明钱-order
    description: Smart Money Order Controller
  - name: 外部兼容接口
    description: Compat Controller
  - name: 接管记录
    description: Take Over Controller
  - name: 操盘手相关
    description: Trader Controller
  - name: 服务器时间
    description: Server Time Controller
  - name: 杠杆分层
    description: Leverage Bracket Controller
  - name: 用户合约相关信息
    description: Account Controller
  - name: 用户满意度反馈
    description: User Satisfaction Feedback Controller
  - name: 用户相关内部接口
    description: Internal User V 2 Controller
  - name: 用户福利-赠金
    description: Welfare Controller
  - name: 用户自动减仓
    description: Auto Deleverage Controller
  - name: 用户设置
    description: User Setting Controller
  - name: 用户资金相关
    description: Balance Controller
  - name: 用户阶梯等级费率
    description: User Step Rate Controller
  - name: 自选交易对
    description: User Collection Controller
  - name: 账户内部接口
    description: Internal Account V 2 Controller
  - name: 资金相关内部接口
    description: Internal Balance V 2 Controller
  - name: 通用功能接口
    description: Common Controller

paths:
  /v1/account/agreement/agree-predict:
    post:
      tags:
        - 用户合约相关信息
      summary: 同意预测合约协议
      operationId: agreePredictAgreementUsingPOST
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                $ref: '#/components/schemas/CommonResponse«boolean»'
        '201':
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found

components:
  schemas:
    "CommonResponse«boolean»":
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: 业务状态码，0 表示成功
        msg:
          type: string
          description: 提示信息
        data:
          type: boolean
          description: 接口返回结果，true 表示成功/已同意
