/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'installation',
        'configuration',
        'playground',
        'typescript-support',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Docusaurus Guides',
        description:
          "Let's learn about the most important Docusaurus concepts!",
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [
        'guides/creating-pages',
        {
          type: 'category',
          label: 'Docs',
          link: {
            type: 'doc',
            id: 'guides/docs/introduction',
          },
          items: [
            'guides/docs/create-doc',
            {
              type: 'category',
              label: 'Sidebar',
              link: {
                type: 'doc',
                id: 'guides/docs/sidebar/index',
              },
              items: [
                'guides/docs/sidebar/items',
                'guides/docs/sidebar/autogenerated',
                'guides/docs/sidebar/multiple-sidebars',
              ],
            },
            'guides/docs/versioning',
            'guides/docs/multi-instance',
          ],
        },
        'blog',
        {
          type: 'category',
          label: 'Markdown Features',
          link: {
            type: 'doc',
            id: 'guides/markdown-features/introduction',
          },
          items: [
            'guides/markdown-features/react',
            'guides/markdown-features/tabs',
            'guides/markdown-features/code-blocks',
            'guides/markdown-features/admonitions',
            'guides/markdown-features/toc',
            'guides/markdown-features/assets',
            'guides/markdown-features/links',
            'guides/markdown-features/plugins',
            'guides/markdown-features/math-equations',
            'guides/markdown-features/diagrams',
            'guides/markdown-features/head-metadata',
          ],
        },
        'styling-layout',
        'swizzling',
        'static-assets',
        'search',
        'browser-support',
        'seo',
        'using-plugins',
        'deployment',
        {
          type: 'category',
          label: 'Internationalization',
          link: {type: 'doc', id: 'i18n/introduction'},
          items: [
            {
              type: 'doc',
              id: 'i18n/tutorial',
              label: 'Tutorial',
            },
            {
              type: 'doc',
              id: 'i18n/git',
              label: 'Using Git',
            },
            {
              type: 'doc',
              id: 'i18n/crowdin',
              label: 'Using Crowdin',
            },
          ],
        },
        'guides/whats-next',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Guides',
      link: {type: 'doc', id: 'advanced/index'},
      items: [
        'advanced/architecture',
        'advanced/plugins',
        'advanced/routing',
        'advanced/ssg',
        'advanced/client',
      ],
    },
    {
      type: 'category',
      label: 'Upgrading',
      link: {
        type: 'doc',
        id: 'migration/index',
      },
      items: [
        'migration/v3',
        // TODO do we want to keep upgrade docs for older Docusaurus versions?
        // It contains links to docs of current version :/
        {
          type: 'category',
          label: 'To Docusaurus v2',
          items: [
            'migration/v2/migration-overview',
            'migration/v2/migration-automated',
            'migration/v2/migration-manual',
            'migration/v2/migration-versioned-sites',
            'migration/v2/migration-translated-sites',
          ],
        },
      ],
    },
  ],
  spot: [
    'spot/index',
    {
      type: 'category',
      label: '下单',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: ['spot/installation'],
    },
  ],
  futures: [
    'futures/index',
    {
      type: 'category',
      label: '期货交易',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: ['futures/installation'],
    },
  ],
  'margin-spot': [
    'margin-spot/index',
    {
      type: 'category',
      label: '保证金现货',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: ['margin-spot/installation'],
    },
  ],
  'copy-trading': [
    'copy-trading/index',
    {
      type: 'category',
      label: '跟单交易',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: ['copy-trading/installation'],
    },
  ],
  'futures-copy': [
    'futures-copy/index',
    {
      type: 'category',
      label: '期货跟单',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: ['futures-copy/installation'],
    },
  ],
  'trading-third-party': [
    'trading-third-party/index',
    {
      type: 'category',
      label: '第三方交易',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: ['trading-third-party/installation'],
    },
  ],
  'user-center': [
    'user-center/index',
    {
      type: 'category',
      label: '用户中心',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: ['user-center/installation'],
    },
  ],
  changelog: ['changelog/index'],
  api: [
    'cli',
    'docusaurus-core',
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
